### ISSUE TITLE
Call to a member function setAttributes() on null

### ISSUE THREAD

**Issue by Danetag** [clubstudioltd/craft3-asset-rev#2]
Hello,

When I override the basic config with `config/assetrev.php`, I get this error:

<img width="1316" alt="screen shot 2017-05-04 at 3 27 39 pm" src="https://cloud.githubusercontent.com/assets/810008/25721387/41a60a52-30de-11e7-83d3-b25a3b91d7f1.png">

`config/assetrev.php`

```
<?php
return array(
    'manifestPath' => '/web/static/assets.json'
);
```

Am I doing anything wrong here?

Thanks!

**Comment by scottwakefield** [comment]
Hi @Danetag,

Ahh, there were some changes in Craft 3 beta 8 that changed the way that settings are handled. A pull request updated the plugin, but a new release wasn't tagged, so you've likely got an outdated version of the plugin.

If you update your `composer.json` to so the plugin require statement looks like this `"clubstudioltd/craft3-asset-rev": "^1.0.0"` and then run composer update, it should pull in the latest version.

Let me know how you get on.

Thanks for reporting the issue! Much appreciated.

Scott

**Comment by Danetag** [comment]
Hi @scottwakefield !

Thank for the quick reply. I actually configured the composer exactly this way already (`"clubstudioltd/craft3-asset-rev": "^1.0.0"`) and I have the issue.

Any chance you push a new release? 🏅 

Thanks!

UPDATE: Oh wait you just did 👍  Thanks!

**Comment by scottwakefield** [comment]
Hi @Danetag,

New release is already pushed, so `composer update` should do the trick. Is it not pulling it in?

New release at: https://github.com/clubstudioltd/craft3-asset-rev/releases/tag/1.0.1

👍

**Comment by scottwakefield** [comment]
No worries @Danetag! Hope the plugin serves you well 👍
